_target_: src.models.abide_ldm_module.AbideLDMModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.diffusion.LatentDiffusion
  hidden_dim: 600
  condition_size: 3
  cond_emb_dim: 64
  diffusion_model:
    _target_: src.models.components.diffusion.GaussianDiffusion
    input_size: 600
    beta_end: 0.1
    diff_steps: 100
    loss_type: l1
    beta_schedule: linear
    denoise_fn:
      _target_: src.models.components.diffusion.EpsilonTheta
      target_dim: 600
      cond_length: 600


# compile model for faster training with pytorch 2.0
compile: false
