_target_: src.models.abide_ldm_pred_module.AbideLDMCLSModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.readout.InferencePredictor
  # label_cls:
  # - 1
  # - 2
  label_key: DX_GROUP
  sample_num: 3
criterion:
  _target_: torch.nn.CrossEntropyLoss

# compile model for faster training with pytorch 2.0
compile: false
